## Data Encryption
### Date : 29 June 2019

- Practice Test on Frequency distribution and combinatorics 
- File / Data Encryption and Decryption
- Python Libraries for Data Science

In [27]:
keyfile = "DataFiles/key.txt"

def generate(keyfile):
    with open(keyfile, 'w') as f:
        for i in range(10):
            if i<6:
                f.write(str(i)+ ' ' + str(i+4)+'\n')
            else:
                f.write(str(i)+ ' ' + str(i-6)+ '\n')
    return
generate(keyfile)

In [28]:
keyfile = "DataFiles/key.txt"
def dictionaryKeyFile(keyfile):
    key = {}
    with open(keyfile, 'r') as f:
        for line in f:
            line = line.split()
            key[line[0]] = line[1]
    return key
dictionaryKeyFile(keyfile)

{'0': '4',
 '1': '5',
 '2': '6',
 '3': '7',
 '4': '8',
 '5': '9',
 '6': '0',
 '7': '1',
 '8': '2',
 '9': '3'}

In [3]:
def encryptMarksData(datafile, keyfile):
    key = dictionaryKeyFile(keyfile)
    with open(datafile, 'r') as f:
        filedata = f.read().split('\n')
    with open('DataFiles/encryptedMarks.txt', 'w') as f:
        for mark in filedata:
            line=''
            for n in mark:
                line += key[n]
            f.write(line+'\n')
    return 
encryptMarksData("DataFiles/marks.txt","DataFiles/key.txt")

In [29]:
# Function to decrypt an encrypted file using same key
def decryptMarksData(encryptedfile, keyfile):
    key = dictionaryKeyFile(keyfile)
    newkey = {}
    for i,j in key.items():
        newkey[j] = i
    with open(encryptedfile, 'r') as f:
        encrypteddata = f.read().split('\n')
    with open('DataFiles/decryptedMarks.txt', 'w') as f:
        for mark in encrypteddata:
            line=''
            for n in mark:
                line += newkey[n]
            f.write(line+'\n')
    return 
decryptMarksData("DataFiles/encryptedMarks.txt","DataFiles/key.txt")

In [34]:
# Comprehensions
keyfile = "DataFiles/key.txt"
key = dictionaryKeyFile(keyfile)

evenkeys = {item for item in key.items() if int(item[0])%2==0}
#evenkeys = {item for item in key}
evenkeys

{('0', '4'), ('2', '6'), ('4', '8'), ('6', '0'), ('8', '2')}

## NumPy Library
 
 - Processing N-Dimensioanl Arrays

In [37]:
import numpy as np

li = [1,2,3]

a = np.array(li) # to convert list to an array

b = np.arange(15)   # generate array elements within a given range
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
rn = np.random.randint(0,100, size=10)
rn

array([51, 68, 65, 93,  1, 68, 21, 41, 17, 62])

In [48]:
m2 = np.random.randint(0,2,size=(3,3))   # To create a matrix of size 3 rows and 3 columns has boolean values
m2

m3 = np.random.randint(0,2,size=(3,3,3))  # To create a Three dimensonal matix
m3

array([[[0, 0, 1],
        [1, 0, 0],
        [0, 1, 1]],

       [[0, 0, 0],
        [1, 1, 0],
        [1, 0, 1]],

       [[0, 0, 0],
        [1, 1, 0],
        [1, 1, 1]]])

In [54]:
m3.ndim
m3.size
m3.shape
m3.dtype
m3.itemsize
m3.nbytes

108

In [55]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [66]:
b.reshape(5,3) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [67]:
import numpy as np

M = np.ones((3,3))
print("Matrix M:\n", M)

Matrix M:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Pandas

**Use cases**
- Data Cleaning
- Data Tranformation
- Data Analysis

**Notations**

- Series
- Dataframes

In [6]:
import pandas as pd

internal1 = {'s1':21, 's2':18, 's3':24}
internal2 = {'s1':15, 's2':18, 's3':12}
internal1 = pd.Series(internal1)
internal1
internal2 = pd.Series(internal2)
internal2

s1    15
s2    18
s3    12
dtype: int64

In [11]:
final = {'Internal1':internal1,'Internal2':internal2}

final = pd.DataFrame(final)
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [12]:
final.columns

Index(['Internal1', 'Internal2'], dtype='object')

In [22]:
final.tail(1)

Internal1  Internal2
s3         24         12

In [23]:
final.tail(2)

Internal1  Internal2
s2         18         18
s3         24         12

In [26]:
final.values

array([[21, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [27]:
final.values[2]

array([24, 12], dtype=int64)

In [28]:
final.values[2,0]
#final.values[2][0]

24

In [34]:
for row in final.values:
    print('Internal1 -',row[0],', Internal2- ',row[1])

Internal1 - 21 , Internal2-  15
Internal1 - 18 , Internal2-  18
Internal1 - 24 , Internal2-  12


In [57]:
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12
s4         15         18

In [58]:
final.values[1] = [16,20]

In [59]:
final

Internal1  Internal2
s1         21         15
s2         16         20
s3         24         12
s4         15         18